import { Component } from '@angular/core';
import { MaterialModule } from '../material/material.module';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-guide',
  standalone: true,
  imports: [
    MaterialModule,
    CommonModule,
  ],
  templateUrl: './guide.component.html',
  styleUrl: './guide.component.scss'
})
export class GuideComponent {
  characters: any[] = [
    {name: 'Archimedes', bio: 'This bird could be considered one of the most knowledgeable beings alive. Having taught himself the various languages in the Nine Kingdoms of Ten, he has memorized almost all written knowledge available to mortals. Frustrated by his limited body, Archimedes desires to become a human. While he lacks the ability to fight, he refuses to run from the right thing.'},
    {name: 'December Evermore', bio: 'This woman has trained her entire life to be a ballerina. While she has the natural ability to manipulate ice, she never trained her powers for combat. She’s normally calm, collected, and slow to anger. There are only two subjects which draw out her passion, dancing and protecting the people she loves.'},
    {name: 'Pearl Guardwell', bio: 'The Princess of Terragard is always polite and proper, living up to her title. Her skills lie in leading others and walking the fine line of politics. Unfortunately, those abilities are little help while her tiny group of allies are being hunted down by hostile forces. Nevertheless, she’s determined to reunite with her betrothed, Josea Mundo.'},
    {name: 'Sir Hellfire', bio: 'Hundreds of years ago, this knight sacrificed his human form to forever serve the heirs of Terragard. Fiercely loyal, he will stop at nothing to protect his allies. Having transformed his old bones into armor, he cannot be permanently injured or killed. Using the flaming sword Inferno, he’s considered one of the most dangerous warriors in the world.'},
  ]
  countriesDescription!: string;
  countries: any[] = [
    {"name": "Atlantis", "description": "This underwater kingdom is located to the north. Filled with water breathing creatures, Atlantis stands out even among the Nine Kingdoms of Ten. With their powerful water and electric magic, they should be considered the most powerful nation in the world. Unfortunately, the land has been plagued by civil wars, coups, and infighting since its founding. There has never been a time of peace in this kingdom. The gods seem content to ignore this land as long as the violence doesn’t spread across the rest of the world."},
    {"name": "Banapolis", "description": "The land of the Animas Superior is the one kingdom that never accepts any immigrants, leaving the powerful humanoid animals as the only occupants. Despite their homogenous nature, the kingdom's magic ability and democracy are top notch. Everything about the flat plains of Banapolis seems ideal, except for the population’s arrogance and discrimination against every other species. Their attitude causes most kingdoms to look at the Animas Superior in contempt."},
    {"name": "Forsaken", "description": "The nation of the gods is located at the southernmost part of the world. There is no division of cities in this land. Every deity and their descendants live here. Nature, magic, and architecture blend together into one across the kingdom. There is a stable peace under the king, queen, and council. Deep beneath the land of the gods is a set of dark secrets that could destroy the world."},
    {"name": "The Frozen Winds", "description": "Surrounded by a giant Ice Wall that runs across the land, this arctic region is cut off from the rest of the world. The only way in is through teleportation or ice manipulation. While the area technically belongs to the Golden Hills, it is unsettled territory. Little lives in this part of the world. The weather is too harsh, even for the gods. Only those with the blessing of the land can survive the tundra."},
    {"name": "Golden Hills", "description": "Previously known as the Fields of Chaos, the Golden Hills is a land made up of banished people and criminals. Under the command of the Supreme Leader Hiccup Erikson, order has spread across the nation. Everyone has a place and a job to perform. They all have to contribute to the betterment of the nation. Any who fail to serve their purpose will be severely punished. Even the weather is manipulated on a daily basis. While many criticize the dictatorship, few can argue with the prosperity that the country has gained in a short period of time."},
    {"name": "Hollowed Rest", "description": "The harsh swamps of this country make most people consider this the most dangerous nation in the world. Hollowed Rest is an intersection for the rest of the multiverse, allowing strange magic and creatures to haunt the kingdom. This country is led by a collection of priests and priestesses. Instead of worshiping the gods, they consider the marshes and ancient creatures to be sacred. This makes policing the area difficult for the fierce and hated Monster Hunters."},
    {"name": "Middleground", "description": "Located at the center of the world, there is no country with a better suited name than this kingdom. A wide desert covers the land. Dangerous creatures patrol the sands. Oddly enough, there are few fatalities from nature in this area. Powerful thrasher worms gift many people with ground manipulation magic. Taming the sea of golden grains is easy for these mages. Unfortunately, little else matters to the people in Middleground. One's worth is measured by their ability to use ground manipulation. The strongest person is always crowned the emperor or empress, no matter their other qualifications."},
    {"name": "Steelspine", "description": "While most countries focus exclusively on magic, Steelspine is the one nation in the Nine Kingdoms of Ten to develop scientifically. Before combining sorcery with machinery, this militaristic land had a bad reputation for aggression and pollution. Despite having reformed hundreds of years ago, most of the other territories view Steelspine with skepticism. With their enchanted robotics and their universal draft into the army, Steelspine is considered one of the most dangerous countries to fight. Only their rival Utopia dares to challenge them in this era of peace."},
    {"name": "Terragard", "description": "Terragard is a land of strict codes of honor. Everyone holds themselves and the people around them to the highest standards possible. The country’s thick jungles are filled with every flying creature imaginable. This is the one nation to worship a god of the Forsaken like an actual deity. In reverence to Ra, everyone in Terragard considers the sky to be sacred. As such, most of the warriors focus exclusively on wielding wind magic. Compared to most of the Nine Kingdoms of Ten, Terragard has faced little conflict with neighboring nations throughout its history. A significant portion of the population is worried that the era of peace is coming to an end."},
    {"name": "Utopia", "description": "In many ways, this land of chilled forests is the most politically deadlocked country in the world. The Utopian Council argues about everything, leaving the nation’s laws stagnant most of the time. Fortunately, their three ancient weapons enforce stability across the land. The Sword of the Soul, the Carnal Amory, and Nirvana are the most powerful tools in the Nine Kingdoms of Ten. Even the gods are afraid of these armaments. Mercifully for most of the territories, all of Utopia’s aggression is focused on their longtime rival Steelspine."},
    {"name": "Zerolands", "description": "Little is known about this country. Few have dared to enter the land of the Dark Mage Zero. This nation is filled with artificial life created by its leader. Zero has used Breath of Life magic to construct a never-ending fighting force. Oddly enough, no one has ever died in conflict with Zerolands. When attacked, the synthetic creatures endure the assault until the invaders grow weary of pointless fighting. Adding to the strangeness, this is the one territory that isn’t allied with a god in the Forsaken."}
  ]

  terminiologies: any[] = [
    {"term": "The Darkest Hour", "description": "The Apocalypse. Armageddon. Ragnarok. Annihilation. The second Great Cataclysm. The End Times. There are many names for the Darkest Hour. This term comes from many different ancient prophecies. While many people don’t believe that the end of the world will come again, some citizens of the Nine Kingdoms of Ten live in perpetual fear that the era of the gods might reach a violent conclusion."},
    {"term": "Dragons", "description": "The giant, flying, fire-breathing reptiles of Terragard are considered sacred in their home country. They have been given the protection of Ra. No one is allowed to disturb them. Many speculate that this is because of how dangerous the dragons are. They are one of the most powerful species alive. Few can fight them. If they rebelled, the era of the gods might come to an end. Fortunately for the Forsaken, these beasts are lazy and selfish. None of them will act unless they’re provoked."},
    {"term": "The Gods", "description": "While they can technically die in battle, the gods of the Forsaken age so slowly that most people consider them immortal. Their natural magic is unrivaled by any other sentient species. Located at the southern end of the world, they demand peace across the Nine Kingdoms of Ten. Almost every country is allied with a deity in the Forsaken Council. The entire world is ruled by the Forsaken’s king and queen."},
    {"term": "The Great Cataclysm", "description": "Over one thousand years ago, the planet was destroyed by a gigantic disaster. No one knows how or why this event occurred. Billions of people died. The world’s ecosystem was completely destroyed. Red energy storms plagued the globe for years. Not even the gods know exactly how the world healed and evolved into an era of magic. Echoes of the catastrophe can be felt in every corner of the world."},
    {"term": "The Ice Wall", "description": "Created hundreds of years ago by the Yuki-Onna, this gigantic frost barrier encircles the Frozen Winds. Completely indestructible, the Ice Wall prevents almost everyone from entering the arctic. Climbing or flying over the enclosure rarely works. The only two means of transportation into the Frozen Winds are teleportation or ice manipulation. Because of the Ice Wall, no one has ever been able to successfully settle the Frozen Winds."},
    {"term": "Leviathans", "description": "Hollowed Rest views these behemoths as sacred. The Leviathans are one of the most powerful beings in the Nine Kingdoms of Ten. They don’t age and can heal from all possible injuries. Few have fought these beasts and survived. Only dragons and gods can rival them. Fortunately, these titans spend their time in slumber. They don’t seem to have any goals. All of the priests and priestesses of Hollowed Rest claim that Leviathans are guardians which protect the Nine Kingdoms of Ten from the dangers of the swamps."},
    {"term": "Munchkins", "description": "These kitten creatures live at the northern peak of the Golden Hills. While their fighting abilities are lower than normal humans, they are skilled workers and laborers. The Golden Hills rely on them for construction and production. They’ve been banished to the North for so long that almost everyone outside of their own kingdom has forgotten about them."},
    {"term": "Rune Knights", "description": "In order to preserve law and order in a country of banished criminals, the Golden Hills needed enforcers. Equipped with magical staffs and War Monsters, these skilled warriors are considered to be elite across the world. They must follow the strict rules of their country at all cost. No one in the Golden Hills is allowed to question them. While they have absolute authority, the Supreme Leader holds them to the highest standards possible. Any rune knight who abuses their power will be put to death."},
    {"term": "Terragard Knights", "description": "Terragard trains their soldiers from a young age. Potential guards start their careers as squires during their teenage years. They train under older knights until they are ready to be on their own. Each soldier is required to follow a strict code of honor. In reverence to the sky, the knights use wind magic to fight. Even among the Nine Kingdoms of Ten, their nationalistic pride is considered to be intimidating."},
    {"term": "War Monsters", "description": "Unlike most magical creatures, War Monsters are not natural. The Animas Superior of Banapolis conducted experiments on these beasts. While the results fused sorcery with their DNA, the mutations shattered the mutants’ minds. Equally deadly and unstable, the War Monsters require a master with a strong will to direct them. If their trainer fails to control them, the creatures will riot, destroying everything in sight."},
    {"term": "Weather Towers", "description": "In order to fight the natural decay of the land, the Golden Hills established a system to manipulate the climate. Dozens of magical skyscrapers are spread across the kingdom. Each of the towers is filled with powerful runes and spinning crystals. The country’s weather is planned weeks in advance. All of the spires need to work in perfect unison for the system to function. Any failure within a pillar can lead to catastrophic results."},
    {"term": "The Wish Stone", "description": "Little is known about the most powerful form of magic in the world. Guarded by the gods, the Wish Stone is capable of altering reality to the whims of the user. Unfortunately, using such sorcery leads to devastating consequences. No one has dared to unleash Wish magic for hundreds of years. Pearl’s Falling Star necklace is the last fragment of the Wish Stone available in the mortal world. For some reason, the gods refuse to reclaim the stone."},
    {"term": "The Yuki-Onna", "description": "Otherwise known as the Snow Woman, the Yuki-Onna is an ancient creature of legend. She appeared hundreds of years ago, created the Ice Wall around the Frozen Winds, and disappeared. No one has seen her since then. A few prophecies speculate her return will bring about the Darkest Hour. Other predictions say that she’s the world’s savior. No one knows the truth, but those that believe in divination notice that December Evermore has similar magic to the Yuki-Onna."}
  ]
  

  ngOnInit() {
    this.countriesDescription = "The Nine Kingdoms of Ten make up the ten countries in the magical world. However, the country of the gods isn’t counted by anyone on this planet, hence the name Nine Kingdoms of Ten. Each nation has vastly different terrains, cultures, and magic preferences. There is an unsteady peace spread across the land. While there are grudges and a desire to fight, the nine kingdoms won’t go to war as long as there is stability among the gods."
  }
  
}
